version: "3.7"
services:
    traefik:
        image: traefik:latest
        command:
            - "--log.level=INFO"
            - "--accesslog=true"
            - "--api=true"
            - "--api.dashboard=true"
            - "--providers.docker=true"
            - "--providers.docker.swarmMode=true"
            - "--providers.docker.exposedByDefault=false"
            - "--providers.file.directory=/traefik-config"
            - "--providers.file.watch=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.websecure.http.tls.certResolver=default"
            - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
            - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
            - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
            - "--certificatesResolvers.default.acme.email=administrator@example.com"
            - "--certificatesResolvers.default.acme.storage=/data/acme.json"
            - "--certificatesResolvers.default.acme.tlsChallenge=true"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "traefik-ssl:/data/"
        ports:
            - target: 80
              protocol: tcp
              published: 80
              mode: ingress
            - target: 443
              protocol: tcp
              published: 443
              mode: ingress
        networks:
            - public
        deploy:
            mode: replicated
            labels:
                traefik.enable: 'true'
                traefik.http.routers.traefik_dashboard.entryPoints: 'websecure'
                traefik.http.routers.traefik_dashboard.service: 'api@internal'
                traefik.http.routers.traefik_dashboard.rule: 'Host(`router.console.example.com`)'
                traefik.http.services.traefik_dummy.loadbalancer.server.port: 19999
            placement:
                constraints:
                    - node.role == manager
    netdata1:
        image: netdata/netdata:latest
        hostname: node-01.example.com
        expose:
            - "19999"
        environment:
            - "PGID=497"
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /cgroup:/host/sys/fs/cgroup:ro
            - netdata_cache:/var/cache/netdata
            - netdata_registry:/var/lib/netdata
            - netdata_config:/etc/netdata
        networks:
            - public
        restart: always
        deploy:
            mode: replicated
            labels:
                traefik.enable: 'true'
                traefik.http.routers.netdata1.entryPoints: 'websecure'
                traefik.http.routers.netdata1.rule: 'Host(`node-01.example.com`)'
                traefik.http.routers.netdata1.tls.certresolver: 'default'
                traefik.http.services.netdata1.loadbalancer.server.port: 19999
            placement:
                constraints:
                    - node.role == manager
networks:
    public:
        external: true
volumes:
    traefik-ssl:
    netdata_cache:
    netdata_registry:
    netdata_config: