version: "3.7"
services:
    traefik:
        image: traefik:latest
        command:
            - "--log.level=INFO"
            - "--accesslog=true"
            - "--api=true"
            - "--api.dashboard=true"
            - "--providers.docker=true"
            - "--providers.docker.swarmMode=true"
            - "--providers.docker.exposedByDefault=false"
            - "--providers.file.directory=/traefik-config"
            - "--providers.file.watch=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.websecure.http.tls.certResolver=default"
            - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
            - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
            - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
            - "--certificatesResolvers.default.acme.email=administrator@example.com"
            - "--certificatesResolvers.default.acme.storage=/data/acme.json"
            - "--certificatesResolvers.default.acme.tlsChallenge=true"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "traefik-ssl:/data/"
        ports:
          - target: 80
            protocol: tcp
            published: 80
            mode: ingress
          - target: 443
            protocol: tcp
            published: 443
            mode: ingress
        networks:
            - public
        deploy:
            mode: replicated
            labels:
                traefik.enable: 'true'
                traefik.http.routers.traefik_dashboard.entryPoints: 'websecure'
                traefik.http.routers.traefik_dashboard.service: 'api@internal'
                traefik.http.routers.traefik_dashboard.rule: 'Host(`router.console.example.com`)'
                traefik.http.services.traefik_dummy.loadbalancer.server.port: 19999
            placement:
                constraints:
                    - node.role == manager
networks:
    public:
        external: true
volumes:
    traefik-ssl: